// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy1YAli_hwSaX0hVP8MI2pjwbMMYiQPdU',
    appId: '1:851551217137:web:fb17ff126a126f68c25050',
    messagingSenderId: '851551217137',
    projectId: 'chat-app-49c03',
    authDomain: 'chat-app-49c03.firebaseapp.com',
    storageBucket: 'chat-app-49c03.firebasestorage.app',
    measurementId: 'G-HR705979SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVaKJLpidjR1_c3Ujj9ruw08PVShqUHoE',
    appId: '1:851551217137:android:71f27f937addeb78c25050',
    messagingSenderId: '851551217137',
    projectId: 'chat-app-49c03',
    storageBucket: 'chat-app-49c03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxA9uq_s1LCWWTu4QYY337-YjPCGECs2o',
    appId: '1:851551217137:ios:3d9b133eebce96bbc25050',
    messagingSenderId: '851551217137',
    projectId: 'chat-app-49c03',
    storageBucket: 'chat-app-49c03.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxA9uq_s1LCWWTu4QYY337-YjPCGECs2o',
    appId: '1:851551217137:ios:3d9b133eebce96bbc25050',
    messagingSenderId: '851551217137',
    projectId: 'chat-app-49c03',
    storageBucket: 'chat-app-49c03.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy1YAli_hwSaX0hVP8MI2pjwbMMYiQPdU',
    appId: '1:851551217137:web:400db0042f59e261c25050',
    messagingSenderId: '851551217137',
    projectId: 'chat-app-49c03',
    authDomain: 'chat-app-49c03.firebaseapp.com',
    storageBucket: 'chat-app-49c03.firebasestorage.app',
    measurementId: 'G-EKPXWVGGJM',
  );
}
